remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: '松鼠'
description: '松鼠的科研札记'
show_downloads: "true"
google_analytics: UA-XXXXXX-X
# Build settings
destination: _site
markdown: kramdown
highlighter: rouge
url: 'https://www.gaohy.cloud'
sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

author:
  name: '松鼠_Gaohy'
  email: gaohy0812@163.com
  github_username:  gaohy0812
