remote_theme: jekyll-uno-timeline

author:
  name: 'Gao Hanyu'
  email: gaohy0812@163.com
  mastodon: tzuehlke@mstdn.social
  twitter_username: thomzuehlke
#  facebook_username: joshgerdes
  github_username:  gaohy0812
  linkedin_username:  thomas-zühlke-889182165
  meetup_name: Azure-Meetup-Rostock-MV
